### PR TITLE
Update turkish locales

### PR DESCRIPTION
**Pull request by mikropsoft**

### CODE REVIEW

**Comment by Sav22999** [comment]
Use Crowdin for translations

**Comment by mikropsoft** [comment]
> Use Crowdin for translations

I guess you didn't specify this on the repo

**Comment by Sav22999** [comment]
https://crowdin.com/project/sav-pdf-viewer

**Comment by Sav22999** [comment]
@mikropsoft You are totally right. So sorry, I haven't specified this on the description of the repository. I'll add it later

**Comment by mikropsoft** [comment]
> @mikropsoft You are totally right. So sorry, I haven't specified this on the description of the repository. I'll add it later

Thanks. If you can give me proofreader authorization, I will upload and approve the files via crowdin.

**Comment by Sav22999** [comment]
@mikropsoft Sure, please write to me on Telegram (@Sav22999) because I need your email to give you permissions.

**Pull request closed without merging**
