### PR TITLE
Migrated configuration scripts from Groovy to Kotlin DSL completely

### PR DESCRIPTION
**Pull request by HarshPanchal18**

### CODE REVIEW

**Comment by Sav22999** [comment]
@HarshPanchal18 I'm not able to build the app with your edits 😢

**Comment by HarshPanchal18** [comment]
The changes are working on my machine as expected.

https://github.com/Sav22999/sav-pdf-viewer-pro/assets/63415584/76557c08-4baf-42e2-9251-8e50b3279eeb

**Comment by Sav22999** [comment]
@HarshPanchal18 Maybe it's because of the conflicting file?

**Comment by Sav22999** [comment]
@HarshPanchal18 Ok, now works correctly. Thanks!

**Comment by HarshPanchal18** [comment]
Great! Can you tell me which file was raising conflicts?

**Comment by Sav22999** [comment]
@HarshPanchal18 I think it was the app/build.gradle

**Pull request merged**
